name: test

on:
  push:

permissions:
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest

    timeout-minutes: 30

    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write

    env:
      TAG: latest

    steps:
      - name: Attest the Docker image
        uses: actions/attest@a2bbfa25375fe432b6a289bc6b6cd05ecd0c4c32 # v4.1.0
        if: false
       
