name: test

on:
  push:

permissions:
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest

    timeout-minutes: 30

    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write

    env:
      TAG: latest

    steps:
      - name: Attest the Docker image
        uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4.1.0
        if: false
       
